// states.js
export const STATES = {
  INICIO: "INICIO",
  MENU: "MENU",
  SOPORTE_TECNICO: "SOPORTE_TECNICO",
  SOPORTE_CORREO: "SOPORTE_CORREO",
  SOPORTE_IMPRESORA: "SOPORTE_IMPRESORA",
  IA: "IA",
  CONFIRMAR_CIERRE: "CONFIRMAR_CIERRE",
  ESCALAR: "ESCALAR"
};
